repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-isort
        args: ["--profile=black"]
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ["--py310-plus"]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        always_run: true
        pass_filenames: false
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake --recursive src/
        language: system
        always_run: true
        pass_filenames: false
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        always_run: true
        pass_filenames: false
      - id: black
        name: black
        entry: poetry run black src/
        language: system
        always_run: true
        pass_filenames: false
