[root]
bronze = "@format {env[ROOT_DATA_DIR]}/storage/bronze"
silver = "@format {env[ROOT_DATA_DIR]}/storage/silver"
gold = "@format {env[ROOT_DATA_DIR]}/storage/gold"

[model]
path = "@format {env[ROOT_MODEL_DIR]/model/model.pkl}"

[ingestion]
reader = "CsvReader"
writer = "ParquetWriter"

    [ingestion.book]
    reader = "@format {this.ingestion.reader}"
    writer = "@format {this.ingestion.writer}"

    [ingestion.book.input]
    path = "@format {env[ROOT_DATA_DIR]}/ingest/books.csv"

    [ingestion.book.output]
    path = "@format {this.root.bronze}/books"
    partition_by = ["ingestion_date"]

    [ingestion.checkout]
    reader = "@format {this.ingestion.reader}"
    writer = "@format {this.ingestion.writer}"

    [ingestion.checkout.input]
    path = "@format {env[ROOT_DATA_DIR]}/ingest/checkouts.csv"

    [ingestion.checkout.output]
    path = "@format {this.root.bronze}/checkouts"
    partition_by = ["ingestion_date"]

    [ingestion.customer]
    reader = "@format {this.ingestion.reader}"
    writer = "@format {this.ingestion.writer}"

    [ingestion.customer.input]
    path = "@format {env[ROOT_DATA_DIR]}/ingest/customers.csv"

    [ingestion.customer.output]
    path = "@format {this.root.bronze}/customers"
    partition_by = ["ingestion_date"]

    [ingestion.library]
    reader = "@format {this.ingestion.reader}"
    writer = "@format {this.ingestion.writer}"

    [ingestion.library.input]
    path = "@format {env[ROOT_DATA_DIR]}/ingest/libraries.csv"

    [ingestion.library.output]
    path = "@format {this.root.bronze}/libraries"
    partition_by = ["ingestion_date"]

[transformation]
reader = "ParquetReader"
writer = "ParquetWriter"

    [transformation.book]
    reader = "@format {this.transformation.reader}"
    writer = "@format {this.transformation.writer}"

    [transformation.book.input]
    path = "@format {this.root.bronze}/books"

    [transformation.book.output]
    path = "@format {this.root.silver}/books.parquet"
    partition_by = []

    [transformation.customer]
    reader = "@format {this.transformation.reader}"
    writer = "@format {this.transformation.writer}"

    [transformation.customer.input]
    path = "@format {this.root.bronze}/customers"

    [transformation.customer.output]
    path = "@format {this.root.silver}/customers.parquet"
    partition_by = []

    [transformation.checkout]
    reader = "@format {this.transformation.reader}"
    writer = "@format {this.transformation.writer}"

    [transformation.checkout.input]
    path = "@format {this.root.bronze}/checkouts"

    [transformation.checkout.output]
    path = "@format {this.root.silver}/checkouts.parquet"
    partition_by = []

    [transformation.library]
    reader = "@format {this.transformation.reader}"
    writer = "@format {this.transformation.writer}"

    [transformation.library.input]
    path = "@format {this.root.bronze}/libraries"

    [transformation.library.output]
    path = "@format {this.root.silver}/libraries.parquet"
    partition_by = []

[aggregation]
reader = "ParquetReader"
writer = "ParquetWriter"

    [aggregation.dataset]
    reader = "@format {this.aggregation.reader}"
    writer = "@format {this.aggregation.writer}"

    [aggregation.dataset.input.book]
    path = "@format {this.root.silver}/books.parquet"

    [aggregation.dataset.input.customer]
    path = "@format {this.root.silver}/customers.parquet"

    [aggregation.dataset.input.checkout]
    path = "@format {this.root.silver}/checkouts.parquet"

    [aggregation.dataset.output]
    path = "@format {this.root.gold}/dataset.parquet"
    partition_by = []
